### ISSUE TITLE
Setting up iOS with FCM + APNs

### ISSUE THREAD

**Issue by reidsolon** [Maxim-Kolmogorov/cordova-plugin-push-notifications#10]
How can I integrate this one into iOS?

**Comment by Maxim-Kolmogorov** [comment]
I don't know, i never worked with Firebase and iOS.

**Comment by Maxim-Kolmogorov** [comment]
Instruction in README.md or u got some error?

**Comment by reidsolon** [comment]
I didn't get any errors, its just I can't make it work on iOS. And also, I'm not getting any registration callbacks.

**Comment by Maxim-Kolmogorov** [comment]
First callback - success, second - error. Look at the second callback result, what does it say?

**Comment by reidsolon** [comment]
I already choose "Allow" but still giving me a "Permission Denied" error callback. Why so?

**Comment by Maxim-Kolmogorov** [comment]
In sumulator?

**Comment by reidsolon** [comment]
yes

**Comment by Maxim-Kolmogorov** [comment]
A, token cannot be obtained in simulator, need real iPhone.

**Comment by Maxim-Kolmogorov** [comment]
Just useful. U may test push notification like this:

https://www.avanderlee.com/workflow/testing-push-notifications-ios-simulator/

**Comment by reidsolon** [comment]
Wow, thank you. Will try to test using the link you provided.
