### ISSUE TITLE
I keep getting "Permission Denied" even though I'm allowing device to get notification

### ISSUE THREAD

**Issue by reidsolon** [Maxim-Kolmogorov/cordova-plugin-push-notifications#11]
I still get "Permission Denied" using a real iPhone device.

**Comment by Maxim-Kolmogorov** [comment]
In Signing & Capabilities you are added Push Notification services?

**Comment by sean-hammon** [comment]
We have Push Notifications enabled for the app on the developer web site. However, what is showing in Xcode is Background Modes > Remote notifications. I can add also Push Notifications as you suggest, however, that project file will get overwritten the next time I build with cordova. That also doesn't help our build server. How do I make this option persist?

**Comment by Maxim-Kolmogorov** [comment]
If I understand you correctly, this really needs to do every time manually. I didn't automate this. You can try use Cordova hooks:

https://cordova.apache.org/docs/en/11.x/guide/appdev/hooks/

Example:

https://github.com/Maxim-Kolmogorov/cordova-plugin-push-notifications/blob/main/hooks/android/configureProjectLevelDependency.js
