### ISSUE TITLE
when the ios app is in the foreground, the message notification cannot be received

### ISSUE THREAD

**Issue by levanax** [Maxim-Kolmogorov/cordova-plugin-push-notifications#17]
I encountered a problem, when the ios app is in the foreground, the message notification cannot be received

  window.pushNotification.tapped((payload) => {
    console.log(payload)
  }, (error) => {
    console.error(error)
  })

device： iPhone14 （IOS16.4）

**Comment by Maxim-Kolmogorov** [comment]
```
document.addEventListener('resume', () => {
  window.pushNotification.tapped((payload) => {
    console.log(payload)
  }, (error) => {
    console.error(error)
  })
})
```

**Comment by levanax** [comment]
Thank you very much for replying despite your busy schedule.
