### ISSUE TITLE
How does one receive the notification payloads?

### ISSUE THREAD

**Issue by luisVargasGu** [Maxim-Kolmogorov/cordova-plugin-push-notifications#2]
Expected behaviour:

You can catch the payloads in an event listener

Actual behaviour:

There are no such listener functions

**Comment by Maxim-Kolmogorov** [comment]
Hi. Thanks for your feedback. I have plans for this, it remains to find time.

**Comment by Maxim-Kolmogorov** [comment]
Added the "tapped" function, it helps to get the "payload" if the application is launched through a notification.
