### ISSUE TITLE
Android: Unresolved reference: swiftecho

### ISSUE THREAD

**Issue by noe2505** [Maxim-Kolmogorov/cordova-plugin-push-notifications#5]
Hello!

Using the following versions:
Cordova 11.0.0
Android 10.1.1

When trying to build, I get an error saying:

e: .../platforms/android/app/src/main/kotlin/notifications/MyFirebaseMessagingService.kt: (17, 13): Unresolved reference: swiftecho

ios seems to work great, thank you for this plugin!

**Comment by Maxim-Kolmogorov** [comment]
Oops... Thank you, I solve the problem.

**Comment by Maxim-Kolmogorov** [comment]
Try now. I made a stupid mistake, importуed MainActivity class via my application namespace.
