### ISSUE TITLE
Android, ClassNotFoundException com.google.firebase.messaging...

### ISSUE THREAD

**Issue by noe2505** [Maxim-Kolmogorov/cordova-plugin-push-notifications#6]
Hey Maxim, it's me again!

Thanks to your fix Android compiles now, however the app crashes upon launching.

Using the following versions:
Cordova 11.0.0
Android 10.1.1

Got the log below from adb logcat:

01-07 16:12:27.766 E/AndroidRuntime(14740): FATAL EXCEPTION: main
01-07 16:12:27.766 E/AndroidRuntime(14740): Process: mx.mydomain.myapp, PID: 14740
01-07 16:12:27.766 E/AndroidRuntime(14740): java.lang.RuntimeException: Unable to instantiate application com.google.firebase.messaging.default_notification_color: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.default_notification_color" on path: DexPathList[[zip file "/data/app/~~yR0Flrdc21TlaXlq0vtoFg==/mx.mydomain.myapp-gcsX-xb3fsazST-aXaB8sQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~yR0Flrdc21TlaXlq0vtoFg==/mx.mydomain.myapp-gcsX-xb3fsazST-aXaB8sQ==/lib/arm64, /system/lib64, /system/system_ext/lib64]]
01-07 16:12:27.766 E/AndroidRuntime(14740): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1332)
01-07 16:12:27.766 E/AndroidRuntime(14740): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7532)
01-07 16:12:27.766 E/AndroidRuntime(14740): 	at android.app.ActivityThread.access$1500(ActivityThread.java:301)
01-07 16:12:27.766 E/AndroidRuntime(14740): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166)
01-07 16:12:27.766 E/AndroidRuntime(14740): 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-07 16:12:27.766 E/AndroidRuntime(14740): 	at android.os.Looper.loop(Looper.java:246)
01-07 16:12:27.766 E/AndroidRuntime(14740): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
01-07 16:12:27.766 E/AndroidRuntime(14740): 	at java.lang.reflect.Method.invoke(Native Method)
01-07 16:12:27.766 E/AndroidRuntime(14740): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
01-07 16:12:27.766 E/AndroidRuntime(14740): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
01-07 16:12:27.766 E/AndroidRuntime(14740): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.default_notification_color" on path: DexPathList[[zip file "/data/app/~~yR0Flrdc21TlaXlq0vtoFg==/mx.mydomain.myapp-gcsX-xb3fsazST-aXaB8sQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~yR0Flrdc21TlaXlq0vtoFg==/mx.mydomain.myapp-gcsX-xb3fsazST-aXaB8sQ==/lib/arm64, /system/lib64, /system/system_ext/lib64]]
01-07 16:12:27.766 E/AndroidRuntime(14740): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
01-07 16:12:27.766 E/AndroidRuntime(14740): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
01-07 16:12:27.766 E/AndroidRuntime(14740): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-07 16:12:27.766 E/AndroidRuntime(14740): 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
01-07 16:12:27.766 E/AndroidRuntime(14740): 	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
01-07 16:12:27.766 E/AndroidRuntime(14740): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1158)
01-07 16:12:27.766 E/AndroidRuntime(14740): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1324)
01-07 16:12:27.766 E/AndroidRuntime(14740): 	... 9 more

EDIT:

It seems like the conflict arises when cordova-plugin-camera-with-exif is also present in the project, I know it may not be a problem with your plugin by itself, but maybe you could take a look?

**Comment by Maxim-Kolmogorov** [comment]
Did you set the default color? Through config.xml

**Comment by noe2505** [comment]
Maxim, thanks again for your help!
I was defining it as "0" like in that section, changed that to "#000000" and this time everything ran perfectly.

Awesome lightweight plugin, I owe you a beer.
