### ISSUE TITLE
use notification channels

### ISSUE THREAD

**Issue by cosmopolit** [Maxim-Kolmogorov/cordova-plugin-push-notifications#8]
I'm new to this topic and i need to send specific messages to individual clients. Is there a way to use NotificationChannels to set a notification identifier which notifications the user will receive?

**Comment by Maxim-Kolmogorov** [comment]
Hm, you may set "client_id" (from your backend) for token and save it database. I do it, in my projects store the token in the client in PostgreSQL)

**Comment by cosmopolit** [comment]
Thanks, i got it. Easy, the token is sent to the server together with a payload. Only one channel is required. I'll see the channelID is hardcoded in the sources.

**Comment by cosmopolit** [comment]
One question: What is the logic when token will refresh (onTokenRefresh) if user will change device or clear app cache? In this case my existing token will be invalidated.

**Comment by Maxim-Kolmogorov** [comment]
channelID - is only functional [Android](https://developer.android.com/training/notify-user/channels). [Picture for example](https://kolmogorov.pro/github/for_osmopolit.png). 

Plus @noe2505 made possible to select [channels](https://github.com/Maxim-Kolmogorov/cordova-plugin-push-notifications/pull/7): need add prop "channel_id" in your payload for [APS.](https://github.com/Maxim-Kolmogorov/cordova-plugin-push-notifications#android-1)

**Comment by Maxim-Kolmogorov** [comment]
> 
I don't remember, you have to read the in documentation Firebase and Apple. I always request a token on login (it's always up to date) and send it to the server.

`
window.pushNotification.registration((token) => {
  console.log(token);
})
`

**Comment by cosmopolit** [comment]
OK, that's a workaround. I prefer simple solutions, as this significantly reduces the follow-up effort for development. Thank you for this lean implementation of the messaging functionality!
